constants = {
    'api_key': '{DATA_GOLF_KEY}',
    'weather_key': '{WEATHER_API_KEY}',
    'location_key': '{LOCATION_API_KEY}',
    'base_url': "https://feeds.datagolf.com",
    'max_requests_per_minute': 84,
    'database_path': '/Users/michaelfuscoletti/Desktop/asbr/data/golf/db/golf_data.db',
    'model_path': '/Users/michaelfuscoletti/Desktop/asbr/data/golf/models/',
    'sql_path': '/Users/michaelfuscoletti/Desktop/asbr/data/golf/sql/',
    'boxplot_columns': ['r_sg_putt','gir'],
    'tours': ['pga'],
    'years': list(range(2017, 2024)),
    'file_format': 'csv',
    'event_id': 'all',
    'url': 'https://feeds.datagolf.com/field-updates?tour=pga&file_format=csv&key=195c3cb68dd9f46d7feaafc4829c',
    'output_directory': '/Users/michaelfuscoletti/Desktop/asbr/data/golf/sims/',
    'num_iterations': 10000,
}
